[package]
name = "interpulation-flat-matrix-benchmark"
version = "0.1.0"
edition = "2024"


[dependencies]
csv = "1.3.1"
ndarray = "0.16.1"
ninterp = "0.7.3"
serde = { version = "1.0.219", features = ["derive"] }
wide = "0.7.33"
rand = { version = "0.8", features = ["small_rng"] }
